'use client';

import { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Search, X, RefreshCw } from 'lucide-react';
import { GlobalHeader } from '@/components/terminal/TerminalHeader';
import { getActivePairs, getCompare } from '@/lib/api';
import type { ComparePair, CompareResponse } from '@/types/market';

const timeframes = ['1m', '5m', '15m', '30m', '1h', '4h', '8h', '1d'];
const lookbacks = ['1h', '4h', '24h', '7d', '30d'];
type CompareState = { pairs: string[]; timeframe: string; lookback: string; marketTier?: number; minimumDataQuality?: number; activeSignalOnly: boolean; };
const metricGroups: Array<[string, Array<[string, keyof ComparePair]>]> = [
  ['Volume comparison', [['Quote volume USDT', 'quoteVolume24h'], ['Relative volume', 'relativeVolume']]],
  ['Liquidity comparison', [['Spread bps', 'spreadBps'], ['Bid depth USDT', 'bidDepthQuote'], ['Ask depth USDT', 'askDepthQuote'], ['Liquidity score', 'liquidityScore'], ['Slippage $100 bps', 'estimatedSlippage100'], ['Slippage $500 bps', 'estimatedSlippage500']]],
  ['Order flow comparison', [['CVD USDT', 'cvd'], ['Book imbalance', 'orderbookImbalance'], ['Spoof score', 'spoofScore']]],
  ['Signal quality comparison', [['Trend', 'trend'], ['Momentum %', 'momentum'], ['ATR %', 'atrPercent'], ['MTF alignment', 'multiTimeframeAlignment'], ['Signal score', 'signalScore'], ['Dynamic threshold', 'dynamicThreshold'], ['Data quality', 'dataQualityScore'], ['Active signal', 'activeSignal']]],
  ['Historical performance', [['Net return %', 'historical'], ['Win rate', 'historical'], ['Sample count', 'historical'], ['Net expectancy %', 'historical'], ['MFE %', 'historical'], ['MAE %', 'historical']]],
];

function parseUrl() {
  const params = new URLSearchParams(window.location.search);
  const pairs = (params.get('pairs') ?? '').split(',').filter(Boolean).slice(0, 4);
  const marketTier = Number(params.get('marketTier'));
  const minimumDataQuality = Number(params.get('minimumDataQuality'));
  return { pairs, timeframe: timeframes.includes(params.get('timeframe') ?? '') ? params.get('timeframe')! : '15m', lookback: lookbacks.includes(params.get('lookback') ?? '') ? params.get('lookback')! : '24h', marketTier: [1, 2, 3].includes(marketTier) ? marketTier : undefined, minimumDataQuality: Number.isFinite(minimumDataQuality) && minimumDataQuality >= 0 && minimumDataQuality <= 100 ? minimumDataQuality : undefined, activeSignalOnly: params.get('activeSignalOnly') === 'true' };
}
function format(value: unknown): string { if (value === null || value === undefined) return 'Partial'; if (typeof value === 'boolean') return value ? 'Yes' : 'No'; if (typeof value === 'number') return new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 }).format(value); return String(value); }
function arrayOrEmpty<T>(value: T[] | null | undefined): T[] { return Array.isArray(value) ? value : []; }
function normalizeCompare(response: CompareResponse): CompareResponse {
  return {
    ...response,
    unavailable: arrayOrEmpty(response.unavailable),
    pairs: arrayOrEmpty(response.pairs).map((pair) => ({
      ...pair,
      pricePerformance: arrayOrEmpty(pair.pricePerformance),
      supportingEvidence: arrayOrEmpty(pair.supportingEvidence),
      contradictingEvidence: arrayOrEmpty(pair.contradictingEvidence),
      partialMetrics: arrayOrEmpty(pair.partialMetrics),
    })),
  };
}
function historical(pair: ComparePair, label: string) { const h = pair.historical; if (label === 'Net return %') return h.netReturn; if (label === 'Win rate') return h.winRate === null ? null : h.winRate * 100; if (label === 'Sample count') return h.sampleCount; if (label === 'Net expectancy %') return h.netExpectancy; if (label === 'MFE %') return h.mfe; return h.mae; }
function highlight(label: string, pairs: ComparePair[], pair: ComparePair) { const value = label === 'Liquidity score' ? pair.liquidityScore : label === 'Spread bps' ? pair.spreadBps : label === 'Spoof score' ? pair.spoofScore : label === 'Orderbook imbalance' ? Math.abs(pair.orderbookImbalance ?? 0) : label === 'Data quality' ? pair.dataQualityScore : label === 'Signal score' ? pair.signalScore : label === 'Net expectancy %' ? pair.historical.netExpectancy : null; if (value === null) return ''; const comparable = pairs.map(p => label === 'Liquidity score' ? p.liquidityScore : label === 'Spread bps' ? p.spreadBps : label === 'Spoof score' ? p.spoofScore : label === 'Orderbook imbalance' ? Math.abs(p.orderbookImbalance ?? 0) : label === 'Data quality' ? p.dataQualityScore : label === 'Signal score' ? p.signalScore : p.historical.netExpectancy).filter((v): v is number => v !== null); const target = (label === 'Spread bps' || label === 'Spoof score') ? Math.min(...comparable) : Math.max(...comparable); if (value !== target) return ''; return label === 'Liquidity score' ? 'Highest liquidity' : label === 'Spread bps' ? 'Lowest spread' : label === 'Spoof score' ? 'Lowest spoof risk' : label === 'Orderbook imbalance' ? 'Strongest order flow' : label === 'Data quality' ? 'Highest data quality' : label === 'Signal score' ? 'Highest signal score' : 'Highest historical net expectancy'; }

export default function ComparePage() {
  const [state, setState] = useState<CompareState | null>(null);
  const [search, setSearch] = useState('');
  const queryClient = useQueryClient();
  const active = useQuery({ queryKey: ['active-pairs'], queryFn: getActivePairs, staleTime: 60_000 });
  const snapshot = useQuery({ queryKey: ['compare', state], queryFn: () => getCompare(state!), enabled: !!state && state.pairs.length >= 2, refetchInterval: 3_000 });
  useEffect(() => setState(parseUrl()), []);
  useEffect(() => { if (state && state.pairs.length === 0 && active.data && active.data.length >= 2) setState({ ...state, pairs: active.data.slice(0, 2).map(pair => pair.Symbol) }); }, [active.data, state]);
  useEffect(() => { if (!state) return; const params = new URLSearchParams({ pairs: state.pairs.join(','), timeframe: state.timeframe, lookback: state.lookback }); if (state.marketTier) params.set('marketTier', String(state.marketTier)); if (state.minimumDataQuality !== undefined) params.set('minimumDataQuality', String(state.minimumDataQuality)); if (state.activeSignalOnly) params.set('activeSignalOnly', 'true'); window.history.replaceState(null, '', `/compare?${params}`); window.dispatchEvent(new CustomEvent('compare-subscription', { detail: { action: 'subscribe', pairs: state.pairs } })); return () => { window.dispatchEvent(new CustomEvent('compare-subscription', { detail: { action: 'unsubscribe', pairs: state.pairs } })); }; }, [state]);
  useEffect(() => { const update = (event: Event) => { const feature = (event as CustomEvent).detail as { symbol: string; price: number; change24hPercent: number; quoteVolume24h: number; relativeVolume1m: number; liquidityScore: number; orderbookImbalance: number; spoofScore: number; trendAlignment: number; ruleScore: number; dataQualityScore: number; dataQualityStatus: ComparePair['dataQualityStatus']; calculatedAt: string }; if (!state?.pairs.includes(feature.symbol)) return; queryClient.setQueryData<CompareResponse>(['compare', state], current => current ? { ...current, pairs: current.pairs.map(pair => pair.symbol === feature.symbol ? { ...pair, price: feature.price, change24hPercent: feature.change24hPercent, quoteVolume24h: feature.quoteVolume24h, relativeVolume: feature.relativeVolume1m, liquidityScore: feature.liquidityScore, orderbookImbalance: feature.orderbookImbalance, spoofScore: feature.spoofScore, multiTimeframeAlignment: feature.trendAlignment, signalScore: feature.ruleScore, dataQualityScore: feature.dataQualityScore, dataQualityStatus: feature.dataQualityStatus, freshness: { ...pair.freshness, lastMarketUpdate: feature.calculatedAt, isStale: false } } : pair) } : current); }; window.addEventListener('compare-update', update); return () => window.removeEventListener('compare-update', update); }, [queryClient, state]);
  if (!state) return null;
  const response = snapshot.data ? normalizeCompare(snapshot.data as CompareResponse) : undefined;
  const selected = new Set(state.pairs);
  const candidates = search ? (active.data ?? []).filter(pair => pair.Symbol.includes(search.toUpperCase()) && !selected.has(pair.Symbol)) : [];
  const setFilter = (key: 'timeframe' | 'lookback', value: string) => setState({ ...state, [key]: value });
  const add = (symbol: string) => { if (state.pairs.length < 4 && !selected.has(symbol)) setState({ ...state, pairs: [...state.pairs, symbol] }); };
  const remove = (symbol: string) => setState({ ...state, pairs: state.pairs.filter(pair => pair !== symbol) });
  return <div className="terminal-app compareApp"><GlobalHeader /><main className="compareShell"><header className="compareHeader"><div><p className="eyebrow">SPOT COMPARISON</p><h1>Pair comparison</h1><p className="muted">Satu snapshot backend. Unit quote volume: USDT.</p></div><button className="icon-btn" aria-label="Refresh compare snapshot" onClick={() => snapshot.refetch()}><RefreshCw size={16} /></button></header><section className="compareControls"><div className="pairPicker"><Search size={15}/><input aria-label="Search active pair" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search active pair"/><div className="pairOptions">{candidates.slice(0, 8).map(pair => <button key={pair.Symbol} onClick={() => add(pair.Symbol)} disabled={state.pairs.length === 4}>{pair.Symbol}<small>Tier {pair.Tier}</small></button>)}</div></div><div className="chips">{state.pairs.map(pair => <span key={pair}>{pair}<button aria-label={`Remove ${pair}`} onClick={() => remove(pair)}><X size={13}/></button></span>)}</div><label>Timeframe<select value={state.timeframe} onChange={e => setFilter('timeframe', e.target.value)}>{timeframes.map(value => <option key={value}>{value}</option>)}</select></label><label>Lookback<select value={state.lookback} onChange={e => setFilter('lookback', e.target.value)}>{lookbacks.map(value => <option key={value}>{value}</option>)}</select></label><label>Tier<select value={state.marketTier ?? ''} onChange={e => setState({ ...state, marketTier: e.target.value ? Number(e.target.value) : undefined })}><option value="">All</option><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></label><label>Min quality<input aria-label="Minimum data quality" type="number" min="0" max="100" value={state.minimumDataQuality ?? ''} onChange={e => setState({ ...state, minimumDataQuality: e.target.value === '' ? undefined : Number(e.target.value) })}/></label><label><input type="checkbox" checked={state.activeSignalOnly} onChange={e => setState({ ...state, activeSignalOnly: e.target.checked })}/> Active signal</label><label className="disabledControl"><input type="checkbox" disabled/> Watchlist only</label></section>{state.pairs.length < 2 && <div className="errorBox">Pilih minimal dua pair aktif untuk membandingkan snapshot.</div>}{snapshot.isLoading && <div className="compareLoading" role="status">Loading comparison snapshot...</div>}{snapshot.isError && <div className="errorBox">Backend offline atau snapshot Compare tidak tersedia.</div>}{response && <CompareContent response={response}/>}</main></div>;
}

function CompareContent({ response }: { response: CompareResponse }) { const pairs = response.pairs; return <><div className="freshness">Snapshot {new Date(response.snapshotAt).toLocaleString()} | Cache {response.cacheTtlSeconds}s</div>{response.unavailable.map(item => <div className="errorBox" key={item.symbol}>{item.symbol}: {item.code} - {item.message}</div>)}<section className="compareTop"><Matrix pairs={pairs}/><PerformanceChart pairs={pairs}/></section>{metricGroups.map(([title, metrics]) => <section className="comparePanel" key={title}><h2>{title}</h2><div className="compareTable"><div className="compareRow compareHead"><strong>Metric</strong>{pairs.map(pair => <strong key={pair.symbol}>{pair.symbol}</strong>)}</div>{metrics.map(([label, key]) => <div className="compareRow" key={label}><span>{label}</span>{pairs.map(pair => { const value = key === 'historical' ? historical(pair, label) : pair[key]; const tag = highlight(label, pairs, pair); return <span key={pair.symbol}>{format(value)} {tag && <small className="compareTag">{tag}</small>}{label === 'Sample count' && pair.historical.insufficientSample && <small className="warningText">Insufficient sample</small>}</span>; })}</div>)}</div></section>)}<section className="comparePanel"><h2>Supporting evidence</h2><Evidence pairs={pairs} field="supportingEvidence"/></section><section className="comparePanel"><h2>Contradicting evidence</h2><Evidence pairs={pairs} field="contradictingEvidence"/></section><section className="comparePanel"><h2>Data freshness status</h2><div className="freshnessGrid">{pairs.map(pair => <div key={pair.symbol}><strong>{pair.symbol}</strong><span>{pair.freshness.isStale ? 'Stale data' : 'Fresh'} | {pair.freshness.bookSynced ? 'Book synced' : 'Book unsynced'}</span><span>Quality: {pair.dataQualityStatus}</span>{pair.partialMetrics.length > 0 && <span>Partial metric: {pair.partialMetrics.join(', ')}</span>}</div>)}</div></section></>; }
function Matrix({ pairs }: { pairs: ComparePair[] }) { return <section className="comparePanel matrix"><h2>Summary matrix</h2><div className="matrixGrid">{pairs.map(pair => <div key={pair.symbol}><strong>{pair.symbol}</strong><span>Rank #{pair.rank} | Tier {pair.tier}</span><b>{format(pair.price)}</b><span className={pair.change24hPercent >= 0 ? 'positiveText' : 'negativeText'}>{format(pair.change24hPercent)}% 24h</span><small>{pair.historical.insufficientSample ? 'Insufficient sample' : `${pair.historical.sampleCount} historical samples`}</small></div>)}</div></section> }
function PerformanceChart({ pairs }: { pairs: ComparePair[] }) { const colors = ['#0ea5e9','#10b981','#f59e0b','#ef4444']; const series = pairs.map(pair => pair.pricePerformance); const longest = Math.max(0, ...series.map(points => points.length)); const values = series.flatMap(points => points.map(point => point.value)); const min = Math.min(0, ...values), max = Math.max(0, ...values), range = max - min || 1; const line = (points: ComparePair['pricePerformance']) => points.map((point, index) => `${(index / Math.max(1, longest - 1)) * 100},${100 - ((point.value - min) / range) * 100}`).join(' '); return <section className="comparePanel perfChart"><h2>Normalized price performance</h2>{longest > 0 ? <svg className="compareChart" viewBox="0 0 100 100" role="img" aria-label="Normalized price performance chart">{pairs.map((pair, index) => <polyline key={pair.symbol} points={line(pair.pricePerformance)} stroke={colors[index]} />)}</svg> : <p className="muted">Partial metric: candle history unavailable.</p>}<div className="chartLines">{pairs.map((pair, index) => <div key={pair.symbol}><span style={{ background: colors[index] }}/>{pair.symbol}: {pair.pricePerformance.length ? `${format(pair.pricePerformance.at(-1)?.value)}%` : 'Partial'}</div>)}</div><p className="muted">Series normalized from first valid close.</p></section> }
function Evidence({ pairs, field }: { pairs: ComparePair[]; field: 'supportingEvidence' | 'contradictingEvidence' }) { return <div className="evidenceGrid">{pairs.map(pair => <div key={pair.symbol}><strong>{pair.symbol}</strong>{pair[field].length ? pair[field].map((value, index) => <span key={`${value}-${index}`}>{value}</span>) : <span>Partial metric</span>}</div>)}</div> }
