'use client';

import { useEffect, useState } from 'react';
import { RotateCcw, Save, ShieldAlert } from 'lucide-react';
import { GlobalHeader } from '@/components/terminal/TerminalHeader';
import { defaultPreferences, localPreferenceRepository, settingsApi, type AdminSetting, type UserPreferences } from '@/lib/settings';
import { useWorkspace, type WorkspaceState } from '@/stores/workspace';

const fields: Array<[string, string, string[]]> = [
  ['theme', 'Theme', ['dark', 'light', 'system']], ['density', 'Density', ['compact', 'comfortable']], ['fontSize', 'Font size', ['small', 'medium', 'large']], ['numberFormat', 'Number format', ['locale', 'compact']], ['timezone', 'Timezone', ['system', 'UTC']], ['currencyDisplay', 'Currency display', ['USDT', 'USD']], ['positiveColor', 'Positive color', ['green', 'blue']], ['negativeColor', 'Negative color', ['red', 'orange']], ['decimalPrecision', 'Decimal precision', ['auto', '2', '4', '8']],
  ['defaultPanelSizes', 'Default panel sizes', ['balanced', 'wide-chart']], ['defaultPair', 'Default pair', ['BTC_USDT', 'ETH_USDT', 'SOL_USDT']], ['defaultTimeframe', 'Default timeframe', ['5m', '15m', '1h']], ['defaultTerminalRoute', 'Default terminal route', ['/terminal/BTC_USDT', '/terminal/ETH_USDT']],
  ['chartProvider', 'Chart provider', ['lightweight']], ['chartType', 'Default chart type', ['candles', 'line', 'bars']], ['minimumSignalScore', 'Minimum signal score', ['70', '80', '90']], ['maximumNotificationsPerHour', 'Maximum notifications/hour', ['5', '20', '50']], ['digestMode', 'Digest mode', ['off', 'hourly', 'daily']], ['defaultWatchlist', 'Default watchlist', ['Default']], ['watchlistTimeframe', 'Preferred timeframe', ['5m', '15m', '1h']], ['defaultAlertScore', 'Default alert score', ['70', '80', '90']], ['defaultRiskFilter', 'Default risk filter', ['LOW', 'LOW,MEDIUM', 'ALL']],
];
const toggles: Array<[string, string]> = [['reduceMotion', 'Reduce motion'], ['chartWatermark', 'Chart watermark'], ['showLeftPairPanel', 'Show left pair panel'], ['showRightSignalPanel', 'Show right signal panel'], ['showDiagnostic', 'Show diagnostic'], ['showOrderBook', 'Show order book'], ['showRecentTrades', 'Show recent trades'], ['signalOverlay', 'Signal overlay'], ['drawingPersistence', 'Drawing persistence'], ['autoScale', 'Auto scale'], ['logarithmicScale', 'Logarithmic scale'], ['browserNotifications', 'Browser notifications'], ['sound', 'Sound'], ['quietHours', 'Quiet hours'], ['systemAlerts', 'System alerts'], ['aiAlerts', 'AI alerts'], ['staleDataAlerts', 'Stale data alerts'], ['orderBookResyncAlerts', 'Order book resync alerts']];
const adminDefaults: Record<string, unknown> = { market_pair_limit: 150, tier_a_limit: 30, tier_b_limit: 50, tier_c_limit: 70, universe_refresh_interval: 10, signal_setup_score: 70, signal_confirm_score: 80, minimum_rule_score: 70, minimum_model_probability: 0.6, minimum_data_quality: 75, maximum_spoof_score: 60, global_active_signal_limit: 15, pair_active_signal_limit: 1, cluster_active_signal_limit: 3, pair_cooldown_minutes: 30, notification_rate_limit: 20, recorder_retention_days: 30, active_rule_version: 'v1', active_model_version: 'v1', ai_provider: 'deterministic', paper_simulation_notionals: [50, 100, 250] };

export default function SettingsPage() {
  const [preferences, setPreferences] = useState<UserPreferences>(defaultPreferences); const [saved, setSaved] = useState('Saved locally'); const [system, setSystem] = useState<Record<string, unknown> | null>(null); const [admin, setAdmin] = useState<AdminSetting[]>([]); const [history, setHistory] = useState<Array<Record<string, unknown>>>([]); const [adminDraft, setAdminDraft] = useState<Record<string, unknown>>(adminDefaults); const [reason, setReason] = useState(''); const [error, setError] = useState('');
  const workspace = useWorkspace();
  useEffect(() => { const loaded = localPreferenceRepository.load(); setPreferences(loaded); applyWorkspace(loaded, workspace); void settingsApi.preferences().then((result) => { const next = { ...loaded, ...result.preferences }; setPreferences(next); localPreferenceRepository.save(next); applyWorkspace(next, workspace); setSaved('Saved to account'); }).catch(() => setSaved('Saved locally')); void settingsApi.system().then(setSystem).catch(() => setError('System status unavailable.')); void settingsApi.admin().then((result) => { setAdmin(result.settings); setAdminDraft({ ...adminDefaults, ...Object.fromEntries(result.settings.map((item) => [item.key, item.value])) }); }).catch(() => {}); void settingsApi.history().then((result) => setHistory(result.auditLogs)).catch(() => {}); }, []);
  function savePreferences(next: UserPreferences) { setPreferences(next); localPreferenceRepository.save(next); applyWorkspace(next, workspace); void settingsApi.savePreferences(next).then(() => setSaved('Saved to account')).catch(() => setSaved('Saved locally')); }
  function update(key: string, value: unknown) { savePreferences({ ...preferences, [key]: value }); }
  function resetLayout() { const next = { ...preferences, ...Object.fromEntries(Object.entries(defaultPreferences).filter(([key]) => key.startsWith('show') || key.startsWith('defaultPanel'))) }; savePreferences(next); workspace.resetLayout(); }
  async function saveAdmin() { setError(''); try { const changed = Object.fromEntries(Object.entries(adminDraft).filter(([key, value]) => admin.find((item) => item.key === key)?.value !== value)); if (!Object.keys(changed).length) return; await settingsApi.saveAdmin(changed, reason); const result = await settingsApi.admin(); setAdmin(result.settings); setReason(''); setSaved('Admin settings saved'); } catch { setError('Admin save rejected. Check role, validation, or backend availability.'); } }
  return <main className="settings-page"><GlobalHeader /><div className="settings-shell"><header className="settings-head"><div><p>CONFIGURATION</p><h1>Settings</h1><span>User preferences apply in this browser. System status never exposes secrets.</span></div><div className="storage-status">{saved}</div></header>{error && <div className="errorBox" role="alert">{error}</div>}
    <Section title="User Settings" text="Appearance"><div className="settings-grid">{fields.slice(0, 9).map(([key, label, options]) => <Select key={key} label={label} value={String(preferences[key])} options={options} onChange={(value) => update(key, numeric(key, value))} />)}{toggles.slice(0, 2).map(([key, label]) => <Toggle key={key} label={label} value={Boolean(preferences[key])} onChange={(value) => update(key, value)} />)}</div></Section>
    <Section title="Terminal Layout" text="Terminal layout"><div className="settings-grid">{fields.slice(9, 13).map(([key, label, options]) => <Select key={key} label={label} value={String(preferences[key])} options={options} onChange={(value) => update(key, value)} />)}{toggles.slice(2, 7).map(([key, label]) => <Toggle key={key} label={label} value={Boolean(preferences[key])} onChange={(value) => update(key, value)} />)}<button className="settings-button" onClick={resetLayout}><RotateCcw size={15} />Reset layout</button></div></Section>
    <Section title="Chart" text="Chart defaults"><div className="settings-grid">{fields.slice(13, 15).map(([key, label, options]) => <Select key={key} label={label} value={String(preferences[key])} options={options} onChange={(value) => update(key, value)} />)}{toggles.slice(7, 11).map(([key, label]) => <Toggle key={key} label={label} value={Boolean(preferences[key])} onChange={(value) => update(key, value)} />)}<button className="settings-button" onClick={() => savePreferences({ ...preferences, chartType: defaultPreferences.chartType, defaultIndicators: defaultPreferences.defaultIndicators, signalOverlay: defaultPreferences.signalOverlay, drawingPersistence: defaultPreferences.drawingPersistence, autoScale: defaultPreferences.autoScale, logarithmicScale: defaultPreferences.logarithmicScale })}><RotateCcw size={15} />Reset chart settings</button></div></Section>
    <Section title="Notifications" text="Notification policy"><div className="settings-grid">{fields.slice(15, 18).map(([key, label, options]) => <Select key={key} label={label} value={String(preferences[key])} options={options} onChange={(value) => update(key, numeric(key, value))} />)}{toggles.slice(11).map(([key, label]) => <Toggle key={key} label={label} value={Boolean(preferences[key])} onChange={(value) => update(key, value)} />)}</div></Section>
    <Section title="Watchlist Default" text="New watchlist defaults"><div className="settings-grid">{fields.slice(18).map(([key, label, options]) => <Select key={key} label={label} value={String(preferences[key])} options={options} onChange={(value) => update(key, numeric(key, value))} />)}</div></Section>
    <Section title="System Settings" text="Read-only backend status"><pre className="settings-system">{system ? JSON.stringify(system, null, 2) : 'Loading system status...'}</pre></Section>
    <Section title="Admin Settings" text="Admin role required. Changes are audited."><div className="admin-preview"><strong>Preview before save</strong><span>Current value: backend value | New value: draft | Effective behavior: per setting reload mode | Restart: marked when required | Validation: backend enforced</span></div><div className="settings-grid">{Object.entries(adminDraft).map(([key, value]) => <label key={key}>{key.replaceAll('_', ' ')}<input value={Array.isArray(value) ? value.join(',') : String(value)} onChange={(event) => setAdminDraft((current) => ({ ...current, [key]: parseAdminValue(value, event.target.value) }))} /></label>)}</div><label className="settings-reason">Reason<input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Required operational context" /></label><button className="settings-button primary" onClick={saveAdmin}><Save size={15} />Save admin settings</button><button className="settings-button" onClick={() => settingsApi.resetAdmin(reason).then(() => { setAdmin([]); setAdminDraft(adminDefaults); setSaved('Admin defaults restored'); }).catch(() => setError('Admin reset rejected.'))}><RotateCcw size={15} />Reset admin defaults</button>{admin.length === 0 && <p className="settings-denied"><ShieldAlert size={15} />Admin API unavailable or role denied.</p>}<h3>Audit history</h3><div className="settings-history">{history.length ? history.map((item, index) => <div key={index}>{String(item.settingKey)}: {JSON.stringify(item.previousValue)} to {JSON.stringify(item.newValue)} | {String(item.result)}</div>) : 'No accessible audit history.'}</div></Section>
  </div></main>;
}
function Section({ title, text, children }: { title: string; text: string; children: React.ReactNode }) { return <section className="settings-section"><header><div><p>{text}</p><h2>{title}</h2></div></header>{children}</section>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <label className="settings-toggle"><input type="checkbox" checked={value} onChange={(event) => onChange(event.target.checked)} />{label}</label>; }
function numeric(key: string, value: string) { return ['minimumSignalScore', 'maximumNotificationsPerHour', 'defaultAlertScore'].includes(key) ? Number(value) : value; }
function parseAdminValue(oldValue: unknown, value: string): unknown { if (Array.isArray(oldValue)) return value.split(',').map(Number).filter((item) => item > 0); if (typeof oldValue === 'number') return Number(value); return value; }
function applyWorkspace(preferences: UserPreferences, workspace: WorkspaceState) { workspace.setTheme(preferences.theme as 'dark' | 'light' | 'system'); workspace.setDensity(preferences.density as 'compact' | 'comfortable'); }
